"""Pydantic models for the PrivateAI API."""

from app.models.open_webui import (
    OpenWebuiEnvConfig,
    OpenWebuiState,
    OpenWebuiStatus,
)
from app.models.cost import (
    BudgetAction,
    BudgetConfig,
    BudgetThreshold,
    CostAlert,
    CostAlertLevel,
    CostReport,
    CostReportDeployment,
    DeploymentCostRecord,
)
from app.models.credentials import AzureCredentials, Credentials
from app.models.deployment import (
    CloudProvider as CloudProviderEnum,
    DeploymentConfig,
    DeploymentRecord,
    DeploymentStatus,
    SecurityLevel,
    ServiceEndpoints,
    SetupConfig,
    StepProgress,
)
from app.models.schemas import (
    AcknowledgeAlertResponse,
    CostAlertsResponse,
    CostReportResponse,
    CreateDeploymentRequest,
    CreateDeploymentResponse,
    DeploymentListResponse,
    DeploymentStatusResponse,
    ErrorResponse,
    OpenWebuiConfigUpdateRequest,
    OpenWebuiConfigUpdateResponse,
    OpenWebuiStartRequest,
    OpenWebuiStartResponse,
    OpenWebuiStatusResponse,
    OpenWebuiStopResponse,
    ProviderInfoResponse,
    ServiceAccessResponse,
    SetBudgetRequest,
    SetBudgetResponse,
    SetDeploymentBudgetRequest,
    SetDeploymentBudgetResponse,
    SetupVMRequest,
    SetupVMResponse,
    ValidateCredentialsRequest,
    ValidateCredentialsResponse,
)

__all__ = [
    "AcknowledgeAlertResponse",
    "AzureCredentials",
    "BudgetAction",
    "BudgetConfig",
    "BudgetThreshold",
    "CloudProviderEnum",
    "CostAlert",
    "CostAlertLevel",
    "CostAlertsResponse",
    "CostReport",
    "CostReportDeployment",
    "CostReportResponse",
    "CreateDeploymentRequest",
    "CreateDeploymentResponse",
    "Credentials",
    "DeploymentConfig",
    "DeploymentCostRecord",
    "DeploymentListResponse",
    "DeploymentRecord",
    "DeploymentStatus",
    "DeploymentStatusResponse",
    "ErrorResponse",
    "OpenWebuiConfigUpdateRequest",
    "OpenWebuiConfigUpdateResponse",
    "OpenWebuiEnvConfig",
    "OpenWebuiStartRequest",
    "OpenWebuiStartResponse",
    "OpenWebuiState",
    "OpenWebuiStatus",
    "OpenWebuiStatusResponse",
    "OpenWebuiStopResponse",
    "ProviderInfoResponse",
    "SecurityLevel",
    "ServiceAccessResponse",
    "ServiceEndpoints",
    "SetBudgetRequest",
    "SetBudgetResponse",
    "SetDeploymentBudgetRequest",
    "SetDeploymentBudgetResponse",
    "SetupConfig",
    "SetupVMRequest",
    "SetupVMResponse",
    "StepProgress",
    "ValidateCredentialsRequest",
    "ValidateCredentialsResponse",
]
